apps/goods/urls.py
from django.conf.urls import url
from django.urls import path, re_path

from .views import Listview,Detailview,indexView

app_name = 'goods'
urlpatterns = [
path('',indexView.as_view(),name='index'),
re_path(r'^list/(?P<type_id>\d+)/(?P<page>\d+)$', Listview.as_view(), name='list'),
path('detail/<int:goods_id>',Detailview.as_view(),name='detail'),






]

apps/user/urls.py
from django.conf.urls import url
from django.urls import path
from .views import RegisterView, LoginView, ActiveView,Userdata,Userdatas,LogoutView

app_name = 'user'
urlpatterns = [

    path('register',RegisterView.as_view(),name='register'),
    path('login',LoginView.as_view(),name='login'),
    url('^active/(.*)$',ActiveView.as_view(),name='active'),#用户激活
    path('userdata',Userdata.as_view(),name='userdata'),
    path('userdatas',Userdatas.as_view(),name='userdatas'),
    path('loginout',LogoutView.as_view(),name='loginout'),







]

extra_apps/DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION
from .widgets import UEditorWidget, AdminUEditorWidget
from .views import get_ueditor_controller
from django.conf.urls import url

urlpatterns = [
    url(r'^controller/$', get_ueditor_controller),
]

extra_apps/rest_framework/urls.py
"""
Login and logout views for the browsable API.

Add these to your root URLconf if you're using the browsable API and
your API requires authentication:

    urlpatterns = [
        ...
        url(r'^auth/', include('rest_framework.urls'))
    ]

You should make sure your authentication settings include `SessionAuthentication`.
"""
from __future__ import unicode_literals

import django
from django.conf.urls import url
from django.contrib.auth import views

if django.VERSION < (1, 11):
    login = views.login
    login_kwargs = {'template_name': 'rest_framework/login.html'}
    logout = views.logout
else:
    login = views.LoginView.as_view(template_name='rest_framework/login.html')
    login_kwargs = {}
    logout = views.LogoutView.as_view()


app_name = 'rest_framework'
urlpatterns = [
    url(r'^login/$', login, login_kwargs, name='login'),
    url(r'^logout/$', logout, name='logout'),
]

lvyou/urls.py
from django.conf.global_settings import MEDIA_ROOT
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

import xadmin
from goods.views import indexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('xadmin/',xadmin.site.urls),
    path('user/', include('user.urls', namespace='user')),
    path('', include('goods.urls', namespace='goods')),

    path('ueditor/', include('DjangoUeditor.urls')),
    #上传路径注册
    re_path(r'media/(?P<path>.*)$',serve,{"document_root": MEDIA_ROOT}),
]

extra_apps/xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getfullargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.urls.base import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass


def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)


def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getfullargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):

    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user,
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user

        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

templates/base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
	<head>
		<meta charset="utf-8" />
		<title></title>
        {% block css %}
		<link rel="stylesheet" href="{% static 'css/index.css' %}" />
        <link rel="stylesheet" href="{% static 'css/main.css' %}" />
        {% endblock css %}
    {% block css2 %}
    {% endblock css2 %}

	</head>

	<body>
    {% block header %}
		<!-- 头部栏 -->
		<header class="clearfix">
			<!-- 头部文字 -->
			<div class="header">
				<div class="container">
					<p>您好，欢迎来到爱旅行！
                        {% if not user.is_authenticated %}
						<a href="{% url 'user:login' %}">登录</a>
						<a href="{% url 'user:register' %}">注册</a>
                        {% endif %}
					</p>
					<ul>
                        {% if user.is_authenticated %}
                            {% if request.session.nickname == None %}
                                <li>  <img height="20" width="20" src="{% static 'home/static/picture/v2-0d96d843ebe08b906f682d06ca5511.jpg' %} "></li>
                        <li>
							<a href="{% url 'user:userdatas' %}">未填写昵称</a>
						</li>



                         <li>
							<a href="{% url 'user:loginout' %}">退出</a>
						</li>

                                {% else %}

                              <li>  <img height="20" width="20" src="{{ request.session.portrait }}"></li>
                          <li>
							<a href="{% url 'user:userdatas' %}">{{ request.session.nickname }}</a>
						</li>




                         <li>
							<a href="{% url 'user:loginout' %}">退出</a>
						</li>
                                {% endif %}
                        {% endif %}
						<li>
							<a href="{% url 'user:userdatas' %}">我的旅行</a>
						</li>
						<li>
							<a href="#">微信</a>
						</li>
						<li>
							<a href="#">客户服务</a>
						</li>
					</ul>
				</div>
			</div>

{% endblock header %}
{% block search %}

			<!-- 头部栏下半部 -->
			<div class="header-down container">
				<img src="{% static 'img/header-img_03.gif' %}" />
				<div class="phone">
					<img src="{% static 'img/phone_06.gif' %}" />
					<p>客户服务热线</p><br />
					<i>12345678</i>
				</div>
				<div class="search">
					<form action="#">
						<select>
							<option value="0">所有产品</option>
							<option value="1">DIVCSS5</option>
						</select>
						<input class="search-text" type="text" value="目的地、主题、签证、或景区名称">
						<div class="header-button">
							<input type="submit" value="搜索">
						</div>
					</form>
				</div>
			</div>
		</header>
    {% endblock search %}

 {% block body %}


  {% endblock body %}

		<!-- 底部栏 -->
 {% block footer %}
		<footer>
			<div class="foot-top">
				<div class="container">
					<div>
						<dl>
							<dt>如何付款和发票</dt>
							<dd>
								<a href="#">hey,yelooer</a>
							</dd>
							<dd>
								<a href="#">hey,yelooer</a>
							</dd>
							<dd>
								<a href="#">hey,yelooer</a>
							</dd>
							<dd>
								<a href="#">hey,yelooer</a>
							</dd>
						</dl>
					</div>
					<hr class="hr" />
					<div>
						<dl>
							<dt>出境游和港澳游常识</dt>
							<dd>
								<a href="#">hey,yelooer</a>
							</dd>
							<dd>
								<a href="#">hey,yelooer</a>
							</dd>
							<dd>
								<a href="#">hey,yelooer</a>
							</dd>
							<dd>
								<a href="#">hey,yelooer</a>
							</dd>
						</dl>
					</div>
					<hr class="hr" />
					<div>
						<dl>
							<dt>预定旅游产品的问题</dt>
							<dd>
								<a href="#">hey,yelooer</a>
							</dd>
							<dd>
								<a href="#">hey,yelooer</a>
							</dd>
							<dd>
								<a href="#">hey,yelooer</a>
							</dd>
						</dl>
					</div>
					<hr class="hr" />
					<div>
						<dl>
							<dt>如何签订旅游合同</dt>
							<dd>
								<a href="#">hey,yelooer</a>
							</dd>
						</dl>
					</div>
					<hr class="hr" />
					<div>
						<dl>
							<dt>会员注册登录方式</dt>
							<dd>
								<a href="#">hey,yelooer</a>
							</dd>
							<dd>
								<a href="#">hey,yelooer</a>
							</dd>
							<dd>
								<a href="#">hey,yelooer</a>
							</dd>
						</dl>
					</div>
					<hr class="hr" />
					<div>
						<dl>
							<dt>如何付款和发票</dt>
							<dd>
								<a href="#"></a>
							</dd>
						</dl>
					</div>
				</div>
			</div>
			<div class="foot-bottom container">
				<p>Copyright © 2019 一生旅行</p>
				<div class="clearfix">
					<ul>
						<li>
							<a href="#"></a>上海旅游协会在线分会</li>
						<li>
							<a href="#"></a>网站备案</li>
						<li>
							<a href="#"></a>网络110</li>
						<li>
							<a href="#"></a>支付宝特约商家</li>
						<li>
							<a href="#"></a>AAA级信用企业</li>
						<li>
							<a href="#"></a>上海工商</li>
						<li>
							<a href="#"></a>可信网站</li>
						<li>
							<a href="#"></a>诚信认证</li>
						<li>
							<a href="#"></a>网络社会征信网</li>
						<li>
							<a href="#"></a>360网站安全检测</li>
					</ul>
				</div>
				<span>
					<i>友情链接：
						<a href="#">网易旅游</a>
						<a href="#">凤凰网旅游</a>
						<a href="#">中国经济网</a>
						<a href="#">雅虎旅游</a>
						<a href="#">百度旅游</a>
						<a href="#">人民网旅游</a>
						<a href="#">中国制造网</a>
						<a href="#">51766旅游网</a>
						<a href="#">欣欣旅游网</a>
						<a href="#">驴妈妈旅游</a>
						<a href="#">网奇艺旅游</a>
						<a href="#">去哪儿</a>
						<a href="#">拉拉勾旅游</a>
						<a href="#">米胖旅游网</a>
						<a href="#">新华网旅游</a>
					</i>

				</span>
			</div>
		</footer>
    {% endblock footer %}

    {% block js %}
    {% endblock js %}

  {% block files %}
    {% endblock files %}

	</body>

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}


 {% block body %}
		<!-- 导航模块大图 -->
		<div class="navigation-module">
			<div class="nav">
				<div class="container">
					<ul>
						<li>
							<a href="#">首页</a>
						</li>
						<li>
							<a href="#">出境旅游</a>
						</li>
						<li>
							<a href="#">国内旅游</a>
						</li>
						<li>
							<a href="#">周边旅游</a>
						</li>
						<li>
							<a href="#">机票</a>
						</li>
						<li>
							<a href="#">客栈酒店</a>
						</li>
						<li>
							<a href="#">景点门票</a>
						</li>
						<li>
							<a href="#">游记攻略</a>
						</li>
					</ul>
				</div>
			</div>
			<div class="banner">
				<div class="container">
					<div class="banner-form">
						<ul>
							<li>
								<h5>1</h5>
								<a href="#">机票</a>
							</li>
							<li>
								<h5>2</h5>
								<a href="#">门票</a>
							</li>
							<li>
								<h5>3</h5>
								<a href="#">酒店</a>
							</li>
							<li>
								<h5>4</h5>
								<a href="#">旅游</a>
							</li>
							<li>
								<h5>5</h5>
								<a href="#">签证</a>
							</li>
						</ul>
						<div class="banner-form-body">
							<div class="banner-form-body-top">
								<p>
									<a href="#">国内机票</a>
									<a href="#">国际机票</a>
								</p>
								<form action="" method="">
									<div class="form-radio">
										航程类型
										<label><input type="radio" name="radio" checked> 单程</label>
										<label><input type="radio" name="radio"> 往返</label>
									</div>
									<div class="form-city">
										往返城市
										<input type="text" value="北京">
										<img src="{% static 'img/tuc27.png' %}">
										<input type="text" value="上海">
									</div>
									<div class="form-date">
										出发时间
										<input type="text" value="2019-03-21">
										<span>返程</span>
										<input type="text" value="yyyy-mm-dd">
									</div>
									<button type="button" class="search-btn">搜 索</button>
								</form>

							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- 中间内容部分 -->
		<!-- 热门推荐模块 -->
		<div class="popular-recom container">
			<div class="popular-recom-head">
				<p>热门推荐<span>爱生活，游世界</span></p>
			</div>
			<div class="popular-recom-body">
				<div class="big-part">
					<img src="{% static 'img/popular-recom_03.gif' %}">
					<div>
						<p>踏青之旅 游玩购物两不误</p>
						<i>￥298.00<b>起</b></i>
					</div>

				</div>
				<div class="big-part">
					<img src="{% static 'img/popular-recom_05.gif' %}">
					<div>
						<p>踏青之旅 游玩购物两不误</p>
						<i>￥298.00<b>起</b></i>
					</div>

				</div>
				<div class="small-part">
					<img src="{% static 'img/popular-recom_07.gif' %}">
					<div>
						<p>扬州瘦西湖</p>
						<i>￥168.00<b>起</b></i>
					</div>

				</div>
				<div class="small-part">
					<img src="{% static 'img/popular-recom_11.gif' %}">
					<div>
						<p>扬州瘦西湖</p>
						<i>￥168.00<b>起</b></i>
					</div>

				</div>
			</div>
		</div>


		<!-- 国内旅游 -->
     {% for country in countrys %}
		<div class="template container">
			<div class="template-head domestic-head">
				<p>{{ country }}</p>
				<span>行走山水间，足迹遍中国</span>
				<i>
					<a href="#">热门推荐</a>
                    {% for sounts in country.image_goods_banners|slice:":5"   %}
					<a href="{% url 'goods:list' country.id 0 %}?city={{ sounts.id  }}">{{ sounts }}</a>
                        {% endfor %}

				</i>
				<div>
					<a href="{% url 'goods:list' country.id 0 %}?city=index">更多{{ country }} > </a>
				</div>
			</div>
			<div class="template-body">
				<div class="template-nav domestic-nav">
					<!-- 热门目的地 -->
					<div class="hot">
						<p>热门目的地</p>
						<ul>
                             {% for sounts in country.image_goods_banners|slice:":12"   %}
							<li>
								<a href="{% url 'goods:list' country.id 0 %}?city={{ sounts.id }}">{{ sounts }}</a>
							</li>
                                  {% endfor %}

						</ul>
					</div>
					<!-- 特色 -->
					<div class="feature">
						<p>热门主题</p>
						<ul>
							<li>
								<a href="#">孝行天下</a>
							</li>
							<li>
								<a href="#">毕业旅行</a>
							</li>
							<li>
								<a href="#">周边踏青</a>
							</li>
							<li>
								<a href="#">山水景观</a>
							</li>
							<li>
								<a href="#">主题乐园</a>
							</li>
							<li>
								<a href="#">节日出游</a>
							</li>
							<li>
								<a href="#">古镇村落</a>
							</li>
							<li>
								<a href="#">金牌产品</a>
							</li>
						</ul>
					</div>
				</div>

             {% for sounts in country.image_goods_banners  %}
                 {% for sount in sounts.goodsskuss %}

				<div class="{{ sount.css_stays }}">
                {% if sount.css_stays == "big-part" %}
				<a  href="{% url 'goods:detail' sount.id  %}">	<img src='  {{ sount.image.url }}'> </a>
                    {% else %}
                  <a href="{% url 'goods:detail' sount.id  %}">  <img width="225" height="141" src=  ' {{ sount.image.url }}'> </a>
                    {% endif %}
					<div>
						<p><a href="{% url 'goods:detail' sount.id  %}"> {{ sount.name|truncatechars:12 }}  </a></p>
						<i>￥{{ sount.price|floatformat:"0" }}<b>起</b></i>
					</div>

				</div>


                     {% endfor %}

				 {% endfor %}

         </div>
		</div>
     {% endfor %}

		<div class="template container tourismstrategy">
			<div class="template-head tourismstrategy-head">
				<p>旅游攻略</p>
				<span>为您提供更多旅途服务</span>
				<div>
					<a href="#">更多攻略 > </a>
				</div>
			</div>
			<div class="template-body tourismstrategy-body">
				<div class="tourismstrategy-body-lef">
					<ul>
						<li>
							<a href="#">【厦门攻略】2014年最新最全最实用厦门旅游攻略 含防骗注意事项</a>
						</li>
						<li>
							<a href="#">【塞班岛旅游】---【走着走着】之遗落在太平洋上的宝石---塞班</a>
						</li>
						<li>
							<a href="#">【台湾旅游】饕餮盛宴在台湾</a>
						</li>
						<li>
							<a href="#">【澳大利亚旅游】澳洲11日（悉尼-墨尔本-凯恩斯）衣食住行攻略</a>
						</li>
						<li>
							<a href="#">【黄山旅游】我们的旅途之南京、扬州、镇江、宏村、黄山</a>
						</li>
					</ul>
				</div>
				<div class="tourismstrategy-body-mid">
					<ul>
						<li>
							<a href="#">【台湾旅游】饕餮盛宴在台湾</a>
						</li>
						<li>
							<a href="#">【澳大利亚旅游】澳洲11日（悉尼-墨尔本-凯恩斯）衣食住行攻略全记</a>
						</li>
						<li>
							<a href="#">【黄山旅游】我们的旅途之南京、扬州、镇江、宏村、黄山</a>
						</li>
						<li>
							<a href="#">【新疆旅游】徒步喀纳斯，看童话里的金秋</a>
						</li>
						<li>
							<a href="#">【韩国旅游】泡菜国7天6夜机票、签证、衣食住行全包4000元</a>
						</li>
					</ul>
				</div>
				<div class="tourismstrategy-body-rig">
					<ul>
						<li>
							<a href="#">【云南旅游】【遇见另一种生活】昆明－大理－双廊－丽江－泸沽湖 </a>
						</li>
						<li>
							<a href="#">【大理旅游】【遇见另一种生活】昆明－大理－双廊－丽江－泸沽湖 </a>
						</li>
						<li>
							<a href="#">【韩国旅游】泡菜国7天6夜机票、签证、衣食住行全包4000元</a>
						</li>
						<li>
							<a href="#">【上海旅游】走进魔都，感受不一样的上海</a>
						</li>
						<li>
							<a href="#">【澳大利亚旅游】澳洲11日（悉尼-墨尔本-凯恩斯）衣食住行攻略全记</a>
						</li>
					</ul>
				</div>
			</div>
		</div>

		<!--合作商家-->
		<div class="template container cooperative">
			<div class="template-head cooperative-head">
				<p>合作商家</p>
				<span>为您提供更多旅途服务</span>
				<div>
					<a href="#">更多商家 > </a>
				</div>
			</div>
			<div class="template-body cooperative-body">
				<a href="#"></a>
				<a href="#"></a>
				<a href="#"></a>
				<a href="#"></a>
				<a href="#"></a>
			</div>
		</div>

    {% endblock body %}

templates/login.html
    {% extends 'base.html' %}
{% load staticfiles %}
        {% block css %}


        <link rel="stylesheet" href="{% static 'css/login.css' %}">
        {% endblock css %}
{% block header %}
{% endblock header %}
{% block search %}
{% endblock search %}
{% block body %}
    <div class="mylogin">
        <div >
            <img src="{% static 'imgs/logo.png' %}" alt="" class="logo">
        </div>
        <div class="login">
            <div class="left">
                <div class="top">
                    <form method="post" action="/user/login">
                        {% csrf_token %}
                    <input type="text" name="user" placeholder="您的账号" class="myInputStyle" autofocus>
                    <input type="password" name="password" placeholder="您的密码" class="myInputStyle">
                    <div class="Text">
                        <p id="hint"></p>
                        <p class="forget">忘记密码？</p>
                    </div>
                    <button class="myBtn">登录</button>
                    </form>
                </div>
                <div class="middle">
                    用合作网站账户直接登录
                    <div class="other">
                        <div><img src="{% static 'imgs/h_wb.png' %}" alt=""><p>微博</p></div>
                        <div><img src="{% static 'imgs/h_qq.png' %}" alt=""><p>QQ</p></div>
                        <div><img src="{% static 'imgs/h_wx.png' %}" alt=""><p>微信</p></div>
                    </div>
                </div>
            </div>
            <div class="right">
                <img src="{% static 'imgs/er.jpg' %}" alt="">
                <p>扫一扫</p>
                <p>下载马蜂窝APP</p>
            </div>
        </div>
        <div class="bottom"><span>还没有账号？</span><a href="{% url 'user:register' %}">马上注册</a></div>
    </div>

    {% block footer %}
{% endblock footer %}
{% endblock body %}

    {% block js %}
    <script src="{% static 'js/login.js' %}"></script>
    {% endblock js %}